### ISSUE TITLE
Confirm package/library name and annotation call site

### ISSUE THREAD

**Issue by iampatbrown** [buildkite/test-collector-swift#10]
## ❕ Problem Statement

There are a few different things that impact how this library is consumed by the end user.

### Repository name/url: `https://github.com/buildkite/collector-swift`

I believe this is fine I'm just including it for context. The package can be added to a project as follows:

```swift
  dependencies: [.package(url: "https://github.com/buildkite/collector-swift")],
```

### Package name: `collector-swift`

This impacts how the users adds the library to a test target. There seems to be two main options here:
1. match the repo name: `collector-swift`
```swift
dependencies: [.product(name: "BuildkiteCollector", package: "collector-swift")]
```
2. match the library name: `BuildkiteCollector`
```swift
dependencies: ["BuildkiteCollector"]
```

I don't know the full implications of each approach, however, I have noticed a shift towards options 2, especially with packages released by Apple. eg. [apple/swift-syntax](https://github.com/apple/swift-syntax/blob/53f3e16941d50ed3bf644fe7b496cc6a1efabde5/Package.swift#L39) and [apple/swift-async-algorithms](https://github.com/apple/swift-async-algorithms/blob/a973b06d06f2be355c562ec3ce031373514b03f5/Package.swift#L6)

**Library name:**: `BuildkiteCollector`

While impacting the above. It is also what will be imported to a project that intends to use test annotations. 

```swift
import BuildkiteCollector
```

**Annotation call site:** `Collector.annotate("Hello annotation")`

The reason for using `Collector.annotate` over something like `BuildkiteCollector.annotate` was to avoid a conflict with the library name and provide a shorter call site. 

`Collector` is an empty enum with a static `annotate` function. I'm unsure if this is the right approach.

## 💬 Task Description

- [ ] Discuss the different options and implications
- [ ] Discuss how to keep consistency across collectors
- [ ] Decide on the names for launch
